language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace